language: generic
dist: xenial
cache: packages

addons: 
  apt: 
    packages: 
      - libarchive-dev
      #Cannot: added since yakkety :-(
      #- singularity-container

install:
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # Check dead links before singularity installs itself
  - rm .travis.yml
  - ./scripts/check_dead_links
  # Singularity
  - sudo ./install_singularity

script:
  # Show the location
  - which singularity
  # Show the singularity version
  - singularity --version
  # Build an image
  - sudo singularity build hello_world.simg shub://singularityhub/ubuntu
  # Run the image
  - singularity run hello_world.simg which cowsay
  - singularity run hello_world.simg cowsay "You did it!"
  # Confirm that there is no cowsay on Travis
  - cowsay "I am absent on Travis" || true
