language: generic
dist: bionic
cache: packages
# go: 1.12 # Does not work

addons: 
  apt: 
    packages: 
      - libarchive-dev
      #Cannot: added since yakkety :-(
      #- singularity-container

# Go installation
#
# Default (v1.11):
# GOROOT: /home/travis/.gimme/versions/go1.11.1.linux.amd64
# Go binary:  /home/travis/.gimme/versions/go1.11.1.linux.amd64/bin/go
#
# New (v1.12):
#
# GOROOT: /usr/local/go
# Go binary: /usr/local/go/bin/go

env:
  - GOROOT=/usr/local/go

install:
  # There should be no go on Travis yet
  - echo $GOROOT
  #- go version
  #- which go
  #- ls /home/travis/.gimme/versions/go1.11.1.linux.amd64/bin
  #- ls /home/travis/.gimme/versions/
  #- rm -rf /home/travis/.gimme/versions/go1.11.1.linux.amd64
  #- go version || true
  #- which go || true
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # Check dead links before singularity installs itself
  - rm .travis.yml
  - ./scripts/check_dead_links
  # Singularity
  - sudo ./install_dependencies
  - sudo apt install go
  #- sudo ./install_go
  #- sudo update-alternatives --set go /usr/local/go/bin/go
  - go version
  - which go
  - sudo ./install_singularity

script:
  # Show the location
  - which singularity
  # Show the singularity version
  - singularity --version
  # Download an image
  - singularity pull library://library/default/ubuntu:18.04 
  # Show the root folder of the Singularity container ...
  - singularity exec ubuntu_18.04.sif ls /
  # ... which is different from Travis' root
  - ls /
  # ... but running it like this, gives the Travis folder :-s
  - singularity exec ubuntu_18.04.sif ls
  # Show the /singularity file ...
  - singularity exec ubuntu_18.04.sif cat /singularity
  # ... which is absent on Travis
  - cat /singularity || true
  # Show the singularity OS version ...
  - singularity exec ubuntu_18.04.sif cat /etc/os-releas* 
  # ... which is different on Travis
  - cat /etc/os-releas*
