language: generic
dist: xenial
cache: packages

addons: 
  apt: 
    packages: 
      - libarchive-dev
      #Cannot: added since yakkety :-(
      #- singularity-container



install:
  # Singularity
  - sudo ./install_singularity
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script:
  # Show the location
  - which singularity
  # Show the singularity version
  - singularity --version
  # Build an image
  - sudo singularity build hello_world.simg shub://singularityhub/ubuntu
  #- singularity build ubuntu.sif library://singularityhub/ubuntu
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
