language: generic
dist: bionic
cache: packages

install:
  # Go, from https://tecadmin.net/install-go-on-ubuntu/
  - wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
  - sudo tar -xf go1.12.7.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOROOT=/usr/local/go
  - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # Singularity
  - sudo ./install_dependencies
  - go version
  - which go
  - sudo ./install_singularity

script:
  # Show the location
  - which singularity
  # Show the singularity version
  - singularity --version
  # Download an image
  - singularity pull library://library/default/ubuntu:18.04 || true
  # Show the root folder of the Singularity container ...
  - singularity exec ubuntu_18.04.sif ls /
  # ... which is different from Travis' root
  - ls /
  # ... but running it like this, gives the Travis folder :-s
  - singularity exec ubuntu_18.04.sif ls
  # Show the /singularity file ...
  - singularity exec ubuntu_18.04.sif cat /singularity
  # ... which is absent on Travis
  - cat /singularity || true
  # Show the singularity OS version ...
  - singularity exec ubuntu_18.04.sif cat /etc/os-releas* 
  # ... which is different on Travis
  - cat /etc/os-releas*
  # Check dead links
  - rm -f *.sif
  - rm *.tar.gz
  - rm -rf singularity
  - ./scripts/check_dead_links || true
