#!/bin/bash

export VERSION=1.12 OS=linux ARCH=amd64 && \
  wget --quiet https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
  sudo tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz && \
  rm go$VERSION.$OS-$ARCH.tar.gz

export PATH=/usr/local/go/bin:$PATH

go version