#!/bin/bash
VERSION=3.2.1
wget https://github.com/sylabs/singularity/releases/download/v$VERSION/singularity-$VERSION.tar.gz
tar xvf singularity-$VERSION.tar.gz
cd singularity
./mconfig
cd builddir
make
sudo make install

