on:
  push:
  pull_request:

name: build_singularity

jobs:
  build_singularity:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: eWaterCycle/setup-singularity@v6
        with:
         singularity-version: 3.6.4

      - name: Show singularity version
        run: singularity version

      - name: Build Container
        env:
          SINGULARITY_RECIPE: Singularity
          OUTPUT_CONTAINER: singularity_example_1.sif
        run: |
         ls 
         if [ -f "${SINGULARITY_RECIPE}" ]; then
              sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
         else
             echo "${SINGULARITY_RECIPE} is not found."
             echo "Present working directory: $PWD"
             ls
         fi

